-- databricks/migrations/platform/0003_seed_lob_group_map.sql
-- Seeds initial LOB to Entra group mappings.
-- Replace <entra-group-id-*> placeholders with real object IDs from Entra ID audit.
-- Entra ID audit is a prerequisite before this migration runs (R8 risk mitigation).
--
-- To add a new LOB: add a new migration script (next number) — do not edit this file.
-- To deactivate a LOB: use 0005_deactivate_lob_*.sql pattern — set is_active = false.
-- Never DELETE rows — always soft delete via is_active = false for audit continuity.

INSERT INTO ${catalog}.config.lob_group_map
    (lob_code, lob_name, entra_group_id, scope, is_active, updated_by)
VALUES
    ('UP',     'Upstream',    '<entra-group-id-upstream>',    'LOB',    true, 'migration-0003'),
    ('DS',     'Downstream',  '<entra-group-id-downstream>',  'LOB',    true, 'migration-0003'),
    ('GF',     'Functions',   '<entra-group-id-functions>',   'LOB',    true, 'migration-0003'),
    ('GLOBAL', 'All LOBs',    '<entra-group-id-global>',      'GLOBAL', true, 'migration-0003');
